name: Exporters TFLite CLI Dynamic Quantization INT8 / Python - Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "optimum/exporters/tasks.py"
      - "optimum/exporters/tflite/**.py"
      - "tests/exporters/**.py"
      - "setup.py"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]

    runs-on: [intel-cpu, 8-cpu, ci]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir torch==2.1.2 torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install .[tests,exporters-tf]

      - name: Test with pytest
        working-directory: tests
        run: |
          pytest exporters/tflite/test_exporters_tflite_cli.py -k "int8_dynamic_quantization" -n auto -s -vvvv --durations=0
