name: Exporters ONNX Timm / Python - Test

on:
  workflow_dispatch:
  schedule:
    - cron: 0 7 * * * # every day at 7am

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]

    runs-on: [intel-cpu, 8-cpu, ci]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies for pytorch export
        run: |
          pip install --upgrade pip
          pip install .[tests,exporters]

      - name: Test with pytest
        working-directory: tests
        env:
          RUN_SLOW: "1"
        run: |
          pytest exporters/onnx -k "timm" -n auto -s -vvvv --durations=0
